In [7]:
import pandas as pd
import numpy as np

In [6]:
input_data = pd.read_csv('/home/riritani/mm-vae/sampletest_hc_pfc_adbxd_paired.csv')
input_data

,0_HC,1_HC,2_HC,3_HC,4_HC,5_HC,6_HC,7_HC,8_HC,9_HC,...,subclass_PFC,cell_type_PFC,SCBID_PFC,MouseID_PFC,Age_PFC,Genotype_PFC,CFM_14_5_snRNA_PFC,14-6-residual_PFC,14-6-Bin_PFC,strain
0,0.676302,-0.676665,0.078104,0.101820,-0.050286,-0.569182,0.081154,0.800699,0.505932,-0.296078,...,045 OB-STR-CTX Inh IMN,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
1,0.172018,0.966423,0.496942,1.107144,0.076093,-0.211712,-0.933045,-0.405398,0.909941,-0.454027,...,004 L6 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
2,0.163937,0.468713,-0.989594,0.604529,0.499586,-0.961112,-0.353588,-0.638915,1.170670,0.631558,...,327 Oligo NN,Oligo,CK19106,1576,14,5,24.44,-0.552464,1,D2
3,-0.426777,0.158656,0.324954,-0.044616,0.572386,1.152624,1.376525,-0.013715,1.080084,0.916855,...,006 L4/5 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
4,0.382461,-0.108576,0.177134,-0.487554,0.113696,0.949302,0.463975,-1.163590,0.063630,0.460321,...,041 OB-in Frmd7 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
5,1.089890,-0.631584,1.390899,-2.092378,1.739342,-0.803180,-0.510201,0.004095,1.055494,1.733506,...,006 L4/5 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
6,0.274091,0.023037,0.151623,-0.016705,-0.539080,0.665615,-0.206216,-0.381870,0.773330,-0.486428,...,320 Astro-OLF NN,Astrocytes,CK19106,1576,14,5,24.44,-0.552464,1,D2
7,0.265677,0.682722,0.023630,-0.742958,0.779196,-0.481166,0.692261,-0.312933,0.626950,-0.161075,...,041 OB-in Frmd7 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
8,-0.751508,-0.223805,-1.432133,-1.806848,2.841026,-1.611655,-2.069498,-0.684887,-1.821375,-2.278759,...,045 OB-STR-CTX Inh IMN,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
9,0.500767,-0.121519,-0.023650,0.842210,-0.741053,0.359422,0.452946,0.733606,1.151447,1.064884,...,035 OB Eomes Ms4a15 Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
10,-0.003228,-0.001873,-0.909017,0.126717,-0.875552,0.149977,0.212501,0.830677,0.448064,-0.089479,...,327 Oligo NN,Oligo,CK19106,1576,14,5,24.44,-0.552464,1,D2
11,-0.424513,-0.472273,0.432845,-0.367306,-0.465687,0.660105,1.181611,0.568559,0.088056,-0.911788,...,041 OB-in Frmd7 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
12,-0.422024,-0.912346,-1.850879,-0.149297,-0.201207,0.228718,1.815156,1.773261,0.246157,0.843358,...,044 OB Dopa-Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
13,0.706778,-0.513678,-1.305183,-0.299287,-0.028258,0.697227,0.392063,-0.039218,-0.204501,-0.065431,...,052 Pvalb Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
14,-0.191844,0.029092,0.124602,0.348275,-0.755912,0.961844,0.759123,0.047636,0.108941,-0.480772,...,044 OB Dopa-Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
15,0.506821,-0.880322,-0.437305,-1.018939,-1.401228,-0.234494,-0.559212,-1.246847,-0.661256,-0.297200,...,030 L6 CT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
16,0.738368,-0.216517,0.510363,-1.717581,0.324708,0.641067,0.863122,1.322888,-0.107969,-0.162786,...,006 L4/5 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
17,0.298666,-0.504345,-0.308803,-0.803848,-0.205414,1.326797,0.044777,-0.068895,-0.615054,-0.401688,...,326 OPC NN,Oligo,CK19106,1576,14,5,24.44,-0.552464,1,D2
18,-1.076106,0.317562,-0.837490,0.166272,-0.449277,0.542748,1.183137,0.307569,0.181385,-0.159897,...,062 STR D2 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
19,-1.720561,0.030052,-2.580058,0.540913,0.098517,0.627522,-0.201783,-0.452250,-0.536510,0.387129,...,022 L5 ET CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2

In [8]:
input_data.iloc[:, :4842]

,0_HC,1_HC,2_HC,3_HC,4_HC,5_HC,6_HC,7_HC,8_HC,9_HC,...,4832_HC,4833_HC,4834_HC,4835_HC,4836_HC,4837_HC,4838_HC,4839_HC,4840_HC,4841_HC
0,0.676302,-0.676665,0.078104,0.101820,-0.050286,-0.569182,0.081154,0.800699,0.505932,-0.296078,...,0.932804,-0.516830,-0.677968,0.069296,-0.550571,-1.576761,0.898527,2.163894,-0.662140,-0.569392
1,0.172018,0.966423,0.496942,1.107144,0.076093,-0.211712,-0.933045,-0.405398,0.909941,-0.454027,...,-0.744916,-0.490282,-0.009168,0.879853,-0.382901,0.899923,0.433290,-0.924368,-1.297404,-0.772446
2,0.163937,0.468713,-0.989594,0.604529,0.499586,-0.961112,-0.353588,-0.638915,1.170670,0.631558,...,0.716749,-0.835114,1.699397,0.558089,-1.356184,0.588846,-0.533011,0.825915,-0.300598,-1.394903
3,-0.426777,0.158656,0.324954,-0.044616,0.572386,1.152624,1.376525,-0.013715,1.080084,0.916855,...,0.818673,-0.786757,-0.053360,0.615738,0.165016,0.027807,0.916838,1.601112,0.119220,1.279900
4,0.382461,-0.108576,0.177134,-0.487554,0.113696,0.949302,0.463975,-1.163590,0.063630,0.460321,...,0.330865,0.055530,-0.442310,1.406949,0.533795,-1.318900,0.670305,1.108259,0.059701,-0.718394
5,1.089890,-0.631584,1.390899,-2.092378,1.739342,-0.803180,-0.510201,0.004095,1.055494,1.733506,...,-1.462642,0.713478,-1.342775,1.676104,1.529094,-1.331704,-0.290830,-1.861237,2.188449,-0.465362
6,0.274091,0.023037,0.151623,-0.016705,-0.539080,0.665615,-0.206216,-0.381870,0.773330,-0.486428,...,-0.513460,-0.280600,-0.772755,0.724440,-0.242383,0.362467,0.013324,0.143852,0.118301,0.429084
7,0.265677,0.682722,0.023630,-0.742958,0.779196,-0.481166,0.692261,-0.312933,0.626950,-0.161075,...,-0.439134,1.461492,0.185608,0.436710,0.261206,-1.039150,0.175715,0.300584,-0.612487,-0.469173
8,-0.751508,-0.223805,-1.432133,-1.806848,2.841026,-1.611655,-2.069498,-0.684887,-1.821375,-2.278759,...,1.783778,1.139880,-1.920963,1.243727,-2.118341,0.045043,-1.178608,0.250832,2.976971,-0.143992
9,0.500767,-0.121519,-0.023650,0.842210,-0.741053,0.359422,0.452946,0.733606,1.151447,1.064884,...,0.397616,0.416081,0.842254,-0.673761,-1.049775,0.270824,1.421147,0.272044,-0.851144,0.192319
10,-0.003228,-0.001873,-0.909017,0.126717,-0.875552,0.149977,0.212501,0.830677,0.448064,-0.089479,...,0.165721,0.640071,0.666622,0.342684,-0.335539,0.266147,-1.011923,0.772275,0.304533,-0.171654
11,-0.424513,-0.472273,0.432845,-0.367306,-0.465687,0.660105,1.181611,0.568559,0.088056,-0.911788,...,1.533756,0.894303,0.520381,-0.856865,0.411279,-0.206524,-1.436761,0.263526,-0.292170,-0.611796
12,-0.422024,-0.912346,-1.850879,-0.149297,-0.201207,0.228718,1.815156,1.773261,0.246157,0.843358,...,-0.904287,-0.889647,0.059197,0.361330,0.018827,-0.228527,0.218079,-0.649656,-0.101221,-1.142184
13,0.706778,-0.513678,-1.305183,-0.299287,-0.028258,0.697227,0.392063,-0.039218,-0.204501,-0.065431,...,1.010206,0.231430,-0.385411,0.005912,0.864088,0.208478,-0.544590,-0.064184,1.110279,-1.509836
14,-0.191844,0.029092,0.124602,0.348275,-0.755912,0.961844,0.759123,0.047636,0.108941,-0.480772,...,-0.381134,-0.635092,0.525582,0.153210,-1.157109,-0.148854,-1.543388,-0.658864,-1.091757,0.435175
15,0.506821,-0.880322,-0.437305,-1.018939,-1.401228,-0.234494,-0.559212,-1.246847,-0.661256,-0.297200,...,1.766754,1.562451,1.300536,1.500835,0.725757,-0.069360,0.102065,0.188311,-0.760317,-0.348534
16,0.738368,-0.216517,0.510363,-1.717581,0.324708,0.641067,0.863122,1.322888,-0.107969,-0.162786,...,-0.622485,0.309207,-2.131530,-0.758714,-2.099107,-0.421056,-1.217526,-1.362880,1.307383,-0.949916
17,0.298666,-0.504345,-0.308803,-0.803848,-0.205414,1.326797,0.044777,-0.068895,-0.615054,-0.401688,...,0.167584,0.746496,-1.045761,0.183999,0.060701,-0.697395,0.050745,0.795111,0.353376,-1.481443
18,-1.076106,0.317562,-0.837490,0.166272,-0.449277,0.542748,1.183137,0.307569,0.181385,-0.159897,...,0.741464,-0.011107,-0.236091,0.509897,1.423043,-0.421066,0.896043,-0.750958,-0.375877,1.690926
19,-1.720561,0.030052,-2.580058,0.540913,0.098517,0.627522,-0.201783,-0.452250,-0.536510,0.387129,...,-0.752666,-0.857044,-0.190541,0.663446,1.551311,-0.085347,-0.373739,-1.090061,-1.414148,0.074569

In [12]:
input_data.iloc[:, 4842+10:-11]

,0_PFC,1_PFC,2_PFC,3_PFC,4_PFC,5_PFC,6_PFC,7_PFC,8_PFC,9_PFC,...,4840_PFC,4841_PFC,4842_PFC,4843_PFC,4844_PFC,4845_PFC,4846_PFC,4847_PFC,4848_PFC,4849_PFC
0,0.602264,-2.212500,-0.182519,1.570980,-1.049360,0.987429,1.215427,1.180784,0.778853,1.476163,...,-0.679786,1.574492,2.336441,0.647412,-1.651679,-1.325765,1.419884,1.578122,2.240335,-2.464070
1,0.735028,0.599550,-1.944762,-0.122280,0.436288,-1.406376,1.068656,0.216077,2.182801,0.354995,...,1.010623,-0.007103,0.307199,-1.086823,-0.890471,-0.110960,0.718700,0.387273,0.097050,0.286517
2,0.996497,0.785619,0.741691,-0.129481,0.961040,-0.548824,-0.004921,-0.391642,-0.992006,-0.233468,...,-0.042323,0.050706,0.806485,-0.335440,0.377300,0.236652,-0.397883,0.617924,-0.923872,0.168495
3,0.924528,1.429656,2.344938,1.232031,2.235700,0.301993,1.138328,-0.071105,1.024693,0.215366,...,0.034793,-0.031429,-0.383094,0.796943,-0.612788,-0.508719,2.121291,0.111371,0.040998,1.207013
4,0.384789,0.622417,0.325365,0.440853,0.361446,0.091107,-0.124770,0.096179,0.190009,-0.158155,...,0.148868,0.090958,-0.876561,-0.492805,-0.572454,-0.469049,-0.117222,-0.220662,0.174659,0.312010
5,-1.205162,2.131977,-0.319437,-0.780922,0.564143,1.312992,0.834285,1.451530,1.664006,-2.391531,...,-1.374471,-0.179687,0.099454,-0.118988,-0.552967,-0.050327,-0.465822,-0.683700,-0.482499,0.447680
6,-2.464568,-0.167185,1.772654,0.571356,-1.064671,0.894206,-0.966956,0.536908,0.031025,0.750926,...,-1.017857,0.960894,0.334761,-1.349219,0.860035,0.265452,-0.209809,0.257943,0.192247,0.843927
7,0.417163,-0.954822,0.388580,0.147649,0.168860,0.642822,0.142516,-0.082974,0.165323,0.456984,...,0.279871,-0.094862,0.135702,-0.300730,0.520373,-0.152013,0.229481,-1.135897,0.307077,0.626696
8,-0.281026,0.207346,0.257329,0.841099,-0.090688,0.135675,0.675616,0.499905,0.344411,-0.151222,...,-0.578648,-0.011060,-0.648767,-0.520522,0.528507,-0.352940,-0.313971,-0.162771,1.056663,-0.837930
9,0.027283,0.482167,0.572323,0.063739,-0.394562,-0.237720,-0.542982,0.265175,0.366765,0.129411,...,-0.342055,0.302815,0.043266,0.098190,-0.688528,-0.112709,-0.082969,0.125172,0.287503,0.821798
10,1.044938,0.469611,-1.146986,0.459842,-0.273338,-0.345706,0.701069,0.947952,-0.735944,0.735568,...,0.287748,-0.369769,-0.186006,-0.655628,0.168962,0.495377,-0.799682,-1.151067,0.631026,1.888013
11,-0.684330,0.556397,-0.165100,0.085795,-0.671190,-0.589778,0.875450,0.361339,0.515036,0.636942,...,0.085895,-0.830269,0.086600,-0.772952,-0.331545,-0.737642,0.531357,-0.342200,0.072467,0.822750
12,0.024783,0.363313,0.653630,0.479420,-1.966631,0.004212,-1.432793,0.780552,-1.713861,0.454654,...,-0.334110,-0.525501,1.236429,-0.024092,0.778530,0.102152,-0.181382,-0.566273,-1.298950,0.728200
13,-1.438317,-0.895024,1.295107,1.064446,2.800427,1.426959,1.319533,1.549488,1.726303,-2.264175,...,0.697646,-2.003923,-0.085494,-2.380930,1.912753,-1.524582,-1.312325,-0.980752,-0.969953,-1.773310
14,0.670286,0.758085,0.390572,0.319482,0.135873,-0.698050,0.089452,0.539904,0.286326,-0.197638,...,-0.119494,-0.252656,-0.607974,-0.507646,0.795092,-1.042251,-0.541286,-1.239706,-0.429422,0.519294
15,-1.550561,0.982052,1.317516,-0.636011,0.135640,0.699176,0.427712,1.650257,1.391907,0.730720,...,2.039241,1.394023,-1.360762,1.280350,0.518396,-1.228342,1.119793,0.984058,-2.064069,-0.265487
16,1.215383,-0.061912,0.350607,0.055149,-0.180232,1.102660,-0.041950,0.051338,0.508237,1.331861,...,3.223784,-0.378226,-0.412799,1.677122,1.860120,0.392689,-1.048294,-1.342028,0.331870,-0.276092
17,0.204773,-0.213688,-0.822274,-2.030830,0.711807,0.251767,-0.475052,-1.113525,0.177439,1.096760,...,-0.705985,-0.931180,2.908503,-0.364590,1.014595,-2.133317,-1.458973,-0.136497,-0.468758,0.148391
18,2.744653,-1.089849,0.723225,2.577719,-0.506132,1.473165,-0.527267,0.008938,-1.199897,-0.073892,...,1.737894,0.364205,-0.083863,-0.030785,1.050655,2.072376,-0.725907,0.101506,-1.028135,1.149539
19,0.520855,-0.053992,-1.448978,0.672784,0.455940,0.842462,-0.550287,-0.829220,-2.196333,0.383756,...,0.439561,1.032935,-2.424819,-0.429106,1.613596,0.729582,0.105276,-1.242853,-0.942155,-1.893170

In [13]:
np.max(input_data.iloc[:, :4842]), np.min(input_data.iloc[:, :4842])

(5.744282563968733, -5.579759642548384)

In [14]:
np.max(input_data.iloc[:, 4842+10:-11]), np.min(input_data.iloc[:, 4842+10:-11])

(5.693899969139805, -5.434118823405305)

In [5]:
PFC_from_HC = pd.read_csv('/home/riritani/mm-vae/results_mmVAE_test/reconPFC_epoch100_vaeHC.csv')
PFC_from_HC

,0,1,2,3,4,5,6,7,8,9,...,subclass_PFC,cell_type_PFC,SCBID_PFC,MouseID_PFC,Age_PFC,Genotype_PFC,CFM_14_5_snRNA_PFC,14-6-residual_PFC,14-6-Bin_PFC,strain
0,0.639866,-2.430303,-0.215739,1.777590,-1.243764,0.972128,1.138454,1.144355,0.809235,1.509371,...,045 OB-STR-CTX Inh IMN,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
1,0.595318,0.910114,-0.701840,0.369552,0.417177,-0.975778,0.947610,0.406412,1.273174,-0.092649,...,004 L6 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
2,0.138625,0.647899,0.338382,0.437217,-0.072501,-0.526149,-0.013975,0.169421,-0.273248,0.235878,...,327 Oligo NN,Oligo,CK19106,1576,14,5,24.44,-0.552464,1,D2
3,1.003537,1.419091,1.927662,0.825882,1.463841,0.290726,0.657007,-0.401214,0.499407,0.440539,...,006 L4/5 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
4,0.041971,0.299534,0.264753,0.145279,-0.073922,-0.153177,-0.119735,0.154312,-0.046415,0.274723,...,041 OB-in Frmd7 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
5,-0.915565,1.890573,-0.339728,-0.614994,0.534290,1.166769,0.888279,1.337784,1.872480,-2.033386,...,006 L4/5 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
6,-0.165380,0.700308,0.631451,0.038563,-0.227675,-0.048693,-0.241456,0.373080,-0.027560,0.465753,...,320 Astro-OLF NN,Astrocytes,CK19106,1576,14,5,24.44,-0.552464,1,D2
7,0.036796,0.247771,0.246809,0.134042,-0.075164,-0.011006,-0.086356,0.157970,-0.063478,0.294747,...,041 OB-in Frmd7 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
8,0.212908,0.173517,0.263727,0.487499,-0.349944,-0.022955,0.128006,0.264243,-0.462079,0.015495,...,045 OB-STR-CTX Inh IMN,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
9,0.011755,0.460663,0.336985,0.168945,-0.138441,-0.178439,-0.187020,0.142544,-0.145836,0.263508,...,035 OB Eomes Ms4a15 Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
10,-0.070037,0.244167,0.313592,-0.043455,-0.028169,0.019127,-0.082943,0.244739,0.023527,0.349785,...,327 Oligo NN,Oligo,CK19106,1576,14,5,24.44,-0.552464,1,D2
11,0.038280,0.294045,0.181192,0.093721,-0.004591,-0.087071,0.009416,0.168409,0.025887,0.257807,...,041 OB-in Frmd7 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
12,-0.066300,0.237097,0.383829,-0.177431,0.040019,0.105826,-0.129000,0.191877,0.096042,0.476762,...,044 OB Dopa-Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
13,-0.745832,-1.210595,0.990632,1.335146,2.823065,1.195231,1.343081,1.700418,1.734525,-1.797194,...,052 Pvalb Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
14,-0.040329,0.378263,0.368541,0.115712,-0.163142,-0.057148,-0.166456,0.218019,-0.075667,0.323119,...,044 OB Dopa-Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
15,-1.343619,0.895853,1.343562,-0.540446,0.166376,0.964218,0.386736,1.748028,1.293353,0.632334,...,030 L6 CT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
16,1.306270,0.296242,0.303065,-0.405030,-0.472223,1.328142,-0.432658,-0.512437,0.447680,1.874959,...,006 L4/5 IT CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2
17,0.057709,-0.271830,-0.176279,-1.838172,1.002163,0.705349,-0.549231,-0.478728,0.175212,1.814923,...,326 OPC NN,Oligo,CK19106,1576,14,5,24.44,-0.552464,1,D2
18,2.132093,-1.150945,0.749816,2.336505,-0.620308,1.428068,-0.626923,0.000962,-0.778720,-0.067408,...,062 STR D2 Gaba,Gaba,CK19106,1576,14,5,24.44,-0.552464,1,D2
19,0.513678,-0.029318,-1.603632,0.493791,0.470558,0.644592,-0.524251,-1.078949,-1.918789,0.518300,...,022 L5 ET CTX Glut,Glut,CK19106,1576,14,5,24.44,-0.552464,1,D2

In [15]:
np.max(PFC_from_HC.iloc[:, :4842]), np.min(PFC_from_HC.iloc[:, :4842])

(5.257877, -6.016019)