In [27]:
import pandas as pd
from data_builder import DataBuilder
from torch.utils.data import DataLoader
import numpy as np

In [2]:
beam_break_data = pd.read_csv('/home/rachel/Desktop/mm-vae_ext2/data/master_binary.csv')
beam_break_data

/tmp/ipykernel_454913/1559551854.py:1: DtypeWarning: Columns (1,2,20079) have mixed types. Specify dtype option on import or set low_memory=False.
  beam_break_data = pd.read_csv('/home/rachel/Desktop/mm-vae_ext2/data/master_binary.csv')

,FlyID,Genotype_SpecSheet,Genotype (F>M),RunName,Monitor,Channel,StartMeta,EndMeta,TimeLen,t0,...,t20062,t20063,t20064,t20065,t20066,t20067,Average bout length/D,Activity/waking min,Genotype (FxM)_specsheet,Genotype (FxM)
0,M106_M118_Ch25,Londonxalrm_1_M,London>alrm,M106,118,25,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,88.206897,2.891771,NaN,NaN
1,M106_M118_Ch26,Londonxalrm_1_M,London>alrm,M106,118,26,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,90.576923,1.933168,NaN,NaN
2,M106_M118_Ch27,Londonxalrm_1_M,London>alrm,M106,118,27,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,62.487179,2.523714,NaN,NaN
3,M106_M118_Ch28,Londonxalrm_1_M,London>alrm,M106,118,28,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,216.083333,1.665618,NaN,NaN
4,M106_M118_Ch29,Londonxalrm_1_M,London>alrm,M106,118,29,139834 | 12 Dec 24 | 13:25:00 | 51 | 0 | 118 |...,161518 | 27 Dec 24 | 14:49:00 | 51 | 0 | 118 |...,21685,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,39.933333,2.639334,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,M96_M48_Ch28,elav>attp2vF,NaN,M96,48,28,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,2.0,1.0,3.0,2.0,1.0,1.0,86.413793,2.272366,NaN,NaN
1359,M96_M48_Ch29,elav>attp2vF,NaN,M96,48,29,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,2.0,2.0,1.0,1.0,2.0,2.0,28.743243,2.505122,NaN,NaN
1360,M96_M48_Ch30,elav>attp2vF,NaN,M96,48,30,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,26.519481,2.455212,NaN,NaN
1361,M96_M48_Ch31,elav>attp2vF,NaN,M96,48,31,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,3.0,0.0,1.0,1.0,0.0,1.0,48.088889,2.453503,NaN,NaN
1362,M96_M48_Ch32,elav>attp2vF,NaN,M96,48,32,161390 | 21 Nov 24 | 12:10:00 | 51 | 0 | 48 | ...,181531 | 5 Dec 24 | 11:51:00 | 51 | 0 | 48 | 0...,20142,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,49.071429,3.204082,NaN,NaN

In [24]:
beam_break_data.columns

Index(['FlyID', 'Genotype_SpecSheet', 'Genotype (F>M)', 'RunName', 'Monitor',
       'Channel', 'StartMeta', 'EndMeta', 'TimeLen', 't0',
       ...
       't20062', 't20063', 't20064', 't20065', 't20066', 't20067',
       'Average bout length/D', 'Activity/waking min',
       'Genotype (FxM)_specsheet', 'Genotype (FxM)'],
      dtype='object', length=20081)

In [3]:
beam_break_data['Genotype_SpecSheet'].unique()

array(['Londonxalrm_1_M', 'Londonxalrm_2_F', 'Londonxalrm_2_M',
       'Londonxalrm_3_F', 'Londonxalrm_3_M', 'Londonxattp2_1_F',
       'Londonxattp2_1_M', 'Londonxattp2_2_F', 'Londonxattp2_2_M',
       'Londonxattp2_3_F', 'Londonxattp2_3_M', 'Londonxattp40_2_F',
       'Londonxattp40_2_M', 'Londonxattp40_3_F', 'Londonxattp40_3_M',
       'Londonxrepo_1_F', 'Londonxrepo_2_F', 'Londonxrepo_2_M',
       'Londonxrepo_3_F', 'Londonxrepo_3_M', 'SwedArcxattp2_1_F',
       'SwedArcxattp2_1_M', 'SwedArcxattp2_3_F', 'SwedArcxattp2_3_M',
       'SwedArcxrepo_1_F', 'SwedArcxrepo_1_M', 'SwedArcxrepo_3_F',
       'SwedArcxrepo_3_M', 'Swedishxattp2_1_F', 'Swedishxattp2_1_M',
       'Swedishxattp2_2_F', 'Swedishxattp2_2_M', 'Swedishxrepo_1_F',
       'Swedishxrepo_1_M', 'Swedishxrepo_2_F', 'Swedishxrepo_2_M',
       'attp2xQA40_1_F', 'attp2xQA40_1_M', 'attp2xQA40_3_F',
       'attp2xQA40_3_M', 'attp2xQA42_1_F', 'attp2xQA42_1_M',
       'attp2xQA42_3_F', 'attp2xQA42_3_M', 'attp2xalrm_1_M',
       'attp2xalrm_3_F', 'attp2xalrm_3_M', 'attp2xrepo_1_F',
       'attp2xrepo_1_M', 'attp2xrepo_2_F', 'attp2xrepo_2_M',
       'attp2xrepo_3_F', 'attp2xrepo_3_M', 'attp40xQA40_3_F',
       'attp40xQA40_3_M', 'attp40xQA42_1_F', 'attp40xQA42_1_M',
       'attp40xQA42_3_F', 'attp40xQA42_3_M', 'attp40xalrm_1_M',
       'attp40xalrm_3_F', 'attp40xalrm_3_M', 'attp40xrepo_1_M',
       'attp40xrepo_2_F', 'attp40xrepo_2_M', 'attp40xrepo_3_F',
       'attp40xrepo_3_M', 'elavQFxQA40_1_F', 'elavQFxQA40_1_M',
       'elavQFxQA40_3_F', 'elavQFxQA40_3_M', 'elavQFxQA42_1_F',
       'elavQFxQA42_1_M', 'elavQFxQA42_3_F', 'elavQFxQA42_3_M',
       'elavQFxattp2_1_F', 'elavQFxattp2_1_M', 'elavQFxattp2_3_F',
       'elavQFxattp2_3_M', 'elavQFxattp40_3_F', 'elavQFxattp40_3_M',
       'attp40xQAb40_F', 'attp40xQAb40_M', 'attp40xQAb42_F',
       'attp40xQAb42_M', 'elavQFxQAb40_F', 'elavQFxQAb40_M',
       'elavQFxQAb42_F', 'elavQFxQAb42_M', 'elavQFxattp40_F',
       'elavQFxattp40_M', nan, 'London>alrmF', 'London>alrmM',
       'London>alrmvF', 'London>attp2F', 'London>attp2M',
       'London>attp2vF', 'London>elavF', 'London>elavvF',
       'London>nsybG4F', 'London>nsybG4M', 'London>nsybG4vF',
       'Swed/elavF', 'Swed>alrmF', 'Swed>alrmvF', 'Swed>attp2F',
       'Swed>attp2M', 'Swed>nsybG4F', 'Swed>nsybG4M', 'Swed>nsybG4vF',
       'SwedArc>alrmF', 'SwedArc>alrmM', 'SwedArc>attp2F',
       'SwedArc>attp2M', 'SwedArc>attp2vF', 'SwedArc>nsybG4F',
       'SwedArc>nsybG4m', 'SwedArc>nsybG4vF', 'alrm>attp2F',
       'alrm>attp2M', 'attp2>nsybG4F', 'attp2>nsybG4M', 'attp2>nsybG4vF',
       'elav>SwedArcM', 'elav>attp2F', 'elav>attp2M', 'elav>attp2vF'],
      dtype=object)

In [4]:
beam_break_data.columns[9:-4]

Index(['t0', 't1', 't2', 't3', 't4', 't5', 't6', 't7', 't8', 't9',
       ...
       't20058', 't20059', 't20060', 't20061', 't20062', 't20063', 't20064',
       't20065', 't20066', 't20067'],
      dtype='object', length=20068)

In [5]:
beam_break_data.iloc[:, 9:-4]

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t20058,t20059,t20060,t20061,t20062,t20063,t20064,t20065,t20066,t20067
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,4.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,1.0,3.0,2.0,1.0,1.0
1359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,3.0,3.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0
1360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0
1361,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,2.0,3.0,0.0,1.0,1.0,0.0,1.0
1362,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
beam_break_data_binned = beam_break_data[['FlyID', 'Genotype_SpecSheet']]
beam_break_data_binned

               FlyID Genotype_SpecSheet
0     M106_M118_Ch25    Londonxalrm_1_M
1     M106_M118_Ch26    Londonxalrm_1_M
2     M106_M118_Ch27    Londonxalrm_1_M
3     M106_M118_Ch28    Londonxalrm_1_M
4     M106_M118_Ch29    Londonxalrm_1_M
...              ...                ...
1358    M96_M48_Ch28       elav>attp2vF
1359    M96_M48_Ch29       elav>attp2vF
1360    M96_M48_Ch30       elav>attp2vF
1361    M96_M48_Ch31       elav>attp2vF
1362    M96_M48_Ch32       elav>attp2vF

[1363 rows x 2 columns]

In [7]:
beam_break_data_binned_length = beam_break_data.iloc[:, 9:-4].shape[1] / 4
beam_break_data_binned_length

5017.0

In [8]:
beam_break_data.iloc[:, 9:-4].values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
beam_data = beam_break_data.iloc[:, 9:-4].values
beam_bins = beam_data.reshape(1363, int(beam_break_data_binned_length), 4)
beam_bins.shape

(1363, 5017, 4)

In [10]:
beam_binned = beam_bins.sum(axis=2)
beam_binned.shape

(1363, 5017)

In [11]:
new_time_columns = [f't{i}' for i in range(int(beam_break_data_binned_length))]
beam_binned_df = pd.DataFrame(
    data = beam_binned, 
    columns=new_time_columns
)
beam_binned_df

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1361,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1362,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [12]:
final_beam_break_binned = pd.concat([beam_break_data_binned, beam_binned_df], axis=1)
final_beam_break_binned

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,M106_M118_Ch25,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,M106_M118_Ch26,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,M106_M118_Ch27,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,M106_M118_Ch28,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,M106_M118_Ch29,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,M96_M48_Ch28,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1359,M96_M48_Ch29,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1360,M96_M48_Ch30,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1361,M96_M48_Ch31,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1362,M96_M48_Ch32,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [13]:
final_beam_break_binned.to_csv('/home/rachel/Desktop/mm-vae_ext2/data/raw_beam_break_binned.csv', index=False)

In [14]:
raw_beam_break_binned = pd.read_csv('/home/rachel/Desktop/mm-vae_ext2/data/raw_beam_break_binned.csv')
raw_beam_break_binned

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,M106_M118_Ch25,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,M106_M118_Ch26,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,M106_M118_Ch27,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,M106_M118_Ch28,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,M106_M118_Ch29,Londonxalrm_1_M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,M96_M48_Ch28,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1359,M96_M48_Ch29,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1360,M96_M48_Ch30,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1361,M96_M48_Ch31,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1362,M96_M48_Ch32,elav>attp2vF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [15]:
raw_beam_break_binned.iloc[:, 2:]

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,16.0,7.0,28.0,1.0,3.0,6.0,27.0,4.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,8.0,7.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,8.0,6.0,9.0,8.0,8.0,7.0,6.0,7.0,7.0
1359,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.0,8.0,6.0,8.0,10.0,8.0,10.0,9.0,6.0
1360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,2.0,0.0,0.0,0.0,3.0,3.0,3.0
1361,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,3.0,3.0,9.0,3.0,4.0,10.0,1.0,5.0,3.0
1362,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,4.0,2.0,6.0,3.0,7.0,2.0,1.0,0.0

In [26]:
beam_binned.shape

(1363, 5017)

In [28]:
def standardizer(input_array):
    mean = np.mean(input_array)
    std = np.std(input_array)
    standardized_array = (input_array - mean) / std
    return standardized_array

In [29]:
beam_binned_standardized = standardizer(beam_binned)
beam_binned_standardized

array([[-0.4335486 , -0.4335486 , -0.4335486 , ..., -0.4335486 ,
        -0.4335486 , -0.4335486 ],
       [-0.4335486 , -0.4335486 , -0.4335486 , ..., -0.4335486 ,
        -0.4335486 , -0.4335486 ],
       [-0.4335486 , -0.4335486 , -0.4335486 , ..., -0.4335486 ,
        -0.4335486 , -0.4335486 ],
       ...,
       [-0.4335486 , -0.4335486 , -0.4335486 , ...,  0.21877295,
         0.21877295,  0.21877295],
       [-0.4335486 , -0.4335486 , -0.4335486 , ..., -0.21610808,
         0.65365398,  0.21877295],
       [-0.4335486 , -0.4335486 , -0.4335486 , ...,  0.00133243,
        -0.21610808, -0.4335486 ]])

In [30]:
new_time_columns = [f't{i}' for i in range(int(beam_break_data_binned_length))]
beam_binned_standardized_df = pd.DataFrame(
    data = beam_binned_standardized, 
    columns=new_time_columns
)
beam_binned_standardized_df

,t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549
1,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549
2,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549
3,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.653654,3.045500,1.088535,5.654786,-0.216108,0.218773,0.871094,5.437345,0.436213,-0.433549
4,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,0.218773,1.305976,1.088535,0.436213,-0.433549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.871094,1.305976,0.871094,1.523416,1.305976,1.305976,1.088535,0.871094,1.088535,1.088535
1359,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,1.740857,1.523416,1.305976,0.871094,1.305976,1.740857,1.305976,1.740857,1.523416,0.871094
1360,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.436213,0.436213,0.436213,0.001332,-0.433549,-0.433549,-0.433549,0.218773,0.218773,0.218773
1361,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.871094,0.218773,0.218773,1.523416,0.218773,0.436213,1.740857,-0.216108,0.653654,0.218773
1362,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,1.088535,1.088535,0.436213,0.001332,0.871094,0.218773,1.088535,0.001332,-0.216108,-0.433549

In [32]:
final_beam_break_standardized_binned = pd.concat([beam_break_data_binned, beam_binned_standardized_df], axis=1)
final_beam_break_standardized_binned

,FlyID,Genotype_SpecSheet,t0,t1,t2,t3,t4,t5,t6,t7,...,t5007,t5008,t5009,t5010,t5011,t5012,t5013,t5014,t5015,t5016
0,M106_M118_Ch25,Londonxalrm_1_M,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549
1,M106_M118_Ch26,Londonxalrm_1_M,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549
2,M106_M118_Ch27,Londonxalrm_1_M,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549
3,M106_M118_Ch28,Londonxalrm_1_M,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.653654,3.045500,1.088535,5.654786,-0.216108,0.218773,0.871094,5.437345,0.436213,-0.433549
4,M106_M118_Ch29,Londonxalrm_1_M,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,0.218773,1.305976,1.088535,0.436213,-0.433549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,M96_M48_Ch28,elav>attp2vF,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.871094,1.305976,0.871094,1.523416,1.305976,1.305976,1.088535,0.871094,1.088535,1.088535
1359,M96_M48_Ch29,elav>attp2vF,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,1.740857,1.523416,1.305976,0.871094,1.305976,1.740857,1.305976,1.740857,1.523416,0.871094
1360,M96_M48_Ch30,elav>attp2vF,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.436213,0.436213,0.436213,0.001332,-0.433549,-0.433549,-0.433549,0.218773,0.218773,0.218773
1361,M96_M48_Ch31,elav>attp2vF,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,0.871094,0.218773,0.218773,1.523416,0.218773,0.436213,1.740857,-0.216108,0.653654,0.218773
1362,M96_M48_Ch32,elav>attp2vF,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,-0.433549,...,1.088535,1.088535,0.436213,0.001332,0.871094,0.218773,1.088535,0.001332,-0.216108,-0.433549

In [33]:
final_beam_break_binned.to_csv('/home/rachel/Desktop/mm-vae_ext2/data/raw_beam_break_standardized_binned.csv', index=False)

In [16]:
batch_size = 128
train_set = DataBuilder(raw_beam_break_binned)
test_set = DataBuilder(raw_beam_break_binned)
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_set, batch_size=len(test_set), shuffle=True)

In [17]:
data, fly_id, genotype = next(iter(train_loader))
print(data.shape)
print(len(fly_id))
print(len(genotype))

torch.Size([128, 5017])
128
128

In [18]:
data

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 3., 6., 3.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [19]:
fly_id

('M96_M80_Ch17',
 'M96_M29_Ch22',
 'M106_M111_Ch6',
 'M106_M112_Ch1',
 'M106_M30_Ch10',
 'M96_M25_Ch8',
 'M153_M28_Ch8',
 'M119_M49_Ch18',
 'M96_M10_Ch25',
 'M106_M15_Ch23',
 'M106_M111_Ch24',
 'M106_M33_Ch17',
 'M96_M57_Ch23',
 'M96_M48_Ch27',
 'M96_M54_Ch22',
 'M96_M48_Ch8',
 'M96_M8_Ch4',
 'M106_M29_Ch3',
 'M106_M7_Ch25',
 'M106_M33_Ch22',
 'M106_M112_Ch21',
 'M119_M48_Ch15',
 'M153_M26_Ch14',
 'M106_M117_Ch9',
 'M119_M48_Ch22',
 'M96_M79_Ch4',
 'M153_M28_Ch4',
 'M106_M24_Ch10',
 'M119_M48_Ch5',
 'M96_M50_Ch18',
 'M106_M14_Ch9',
 'M106_M25_Ch25',
 'M96_M10_Ch11',
 'M96_M55_Ch22',
 'M106_M30_Ch24',
 'M96_M54_Ch26',
 'M106_M29_Ch18',
 'M106_M119_Ch32',
 'M96_M48_Ch31',
 'M106_M119_Ch7',
 'M106_M117_Ch28',
 'M106_M4_Ch30',
 'M96_M50_Ch10',
 'M153_M27_Ch29',
 'M96_M54_Ch25',
 'M96_M48_Ch17',
 'M119_M49_Ch23',
 'M106_M15_Ch19',
 'M119_M49_Ch7',
 'M96_M9_Ch23',
 'M119_M50_Ch2',
 'M96_M29_Ch28',
 'M96_M82_Ch6',
 'M106_M33_Ch21',
 'M96_M56_Ch10',
 'M153_M27_Ch8',
 'M96_M54_Ch16',
 'M96_M76_Ch30',
 'M119_M50_Ch15',
 'M96_M56_Ch26',
 'M106_M118_Ch20',
 'M153_M28_Ch26',
 'M106_M29_Ch13',
 'M106_M119_Ch5',
 'M106_M22_Ch22',
 'M96_M10_Ch27',
 'M96_M76_Ch16',
 'M106_M30_Ch19',
 'M106_M119_Ch6',
 'M96_M56_Ch25',
 'M106_M13_Ch4',
 'M106_M29_Ch29',
 'M106_M13_Ch3',
 'M106_M115_Ch22',
 'M96_M80_Ch4',
 'M106_M22_Ch12',
 'M106_M16_Ch6',
 'M119_M50_Ch5',
 'M106_M115_Ch6',
 'M106_M24_Ch4',
 'M96_M9_Ch6',
 'M96_M10_Ch9',
 'M96_M57_Ch2',
 'M106_M16_Ch7',
 'M96_M9_Ch15',
 'M106_M7_Ch26',
 'M106_M4_Ch23',
 'M96_M49_Ch21',
 'M96_M49_Ch10',
 'M106_M118_Ch13',
 'M96_M25_Ch19',
 'M106_M30_Ch17',
 'M106_M111_Ch3',
 'M96_M49_Ch30',
 'M106_M7_Ch7',
 'M119_M50_Ch26',
 'M106_M118_Ch26',
 'M106_M29_Ch21',
 'M96_M54_Ch19',
 'M96_M9_Ch12',
 'M96_M49_Ch7',
 'M96_M25_Ch10',
 'M153_M27_Ch31',
 'M106_M119_Ch17',
 'M96_M56_Ch11',
 'M106_M117_Ch21',
 'M96_M50_Ch30',
 'M106_M24_Ch20',
 'M119_M50_Ch9',
 'M106_M33_Ch9',
 'M96_M50_Ch27',
 'M119_M49_Ch4',
 'M106_M4_Ch31',
 'M106_M116_Ch10',
 'M106_M7_Ch16',
 'M96_M25_Ch2',
 'M96_M82_Ch1',
 'M106_M116_Ch23',
 'M106_M112_Ch9',
 'M106_M24_Ch6',
 'M106_M118_Ch5',
 'M119_M50_Ch28',
 'M96_M10_Ch8',
 'M96_M55_Ch4',
 'M96_M79_Ch27',
 'M96_M80_Ch14',
 'M106_M30_Ch18',
 'M96_M80_Ch7')

In [23]:
genotype

('SwedArc>attp2F',
 'attp2>nsybG4F',
 'attp40xQA42_3_M',
 'Londonxattp2_3_M',
 'attp2xQA40_1_F',
 'Swed>nsybG4vF',
 nan,
 'elavQFxattp40_F',
 'SwedArc>nsybG4F',
 'SwedArcxrepo_1_M',
 'attp40xQA42_1_M',
 'attp40xQA40_3_M',
 'London>elavvF',
 'elav>attp2vF',
 'Swed>alrmF',
 'elav>SwedArcM',
 'London>nsybG4M',
 'elavQFxQA42_1_M',
 'elavQFxQA40_3_F',
 'attp40xQA40_3_M',
 'Londonxattp2_2_M',
 'elavQFxQAb42_M',
 nan,
 'Londonxrepo_2_F',
 'attp40xQAb42_F',
 'London>attp2vF',
 nan,
 'Swedishxrepo_2_F',
 'elavQFxQAb42_F',
 'London>alrmF',
 'Swedishxattp2_2_F',
 'SwedArcxattp2_1_F',
 'SwedArc>nsybG4m',
 'elav>attp2F',
 'attp2xQA42_3_M',
 'Swed>alrmF',
 'attp2xQA40_3_M',
 'attp2xrepo_2_F',
 'elav>attp2vF',
 'attp2xrepo_3_M',
 'Londonxalrm_3_M',
 'elavQFxattp2_1_F',
 'London>alrmM',
 nan,
 'Swed>alrmF',
 'elav>attp2vF',
 'elavQFxattp40_F',
 'SwedArcxrepo_1_M',
 'attp40xQAb42_M',
 'SwedArc>nsybG4vF',
 'elavQFxattp40_M',
 'attp2>nsybG4F',
 'Swed>attp2M',
 'attp40xQA40_3_M',
 'alrm>attp2M',
 nan,
 'Swed>alrmvF',
 'London>attp2F',
 'attp40xQAb40_F',
 'alrm>attp2F',
 'Londonxalrm_2_F',
 nan,
 'elavQFxQA42_1_F',
 'attp2xrepo_3_M',
 'attp40xrepo_3_F',
 'SwedArc>nsybG4F',
 'London>attp2M',
 'attp2xQA42_3_M',
 'attp2xrepo_3_M',
 'alrm>attp2F',
 'elavQFxQA40_1_M',
 'attp2xQA40_3_F',
 'elavQFxQA40_1_M',
 'Londonxattp40_3_M',
 'SwedArc>attp2M',
 'attp40xrepo_3_M',
 'attp40xrepo_2_F',
 'elavQFxQAb40_F',
 'Londonxattp2_1_M',
 'Swedishxrepo_2_M',
 'London>nsybG4vF',
 'SwedArc>nsybG4m',
 'London>elavF',
 'attp40xrepo_1_M',
 'London>nsybG4vF',
 'elavQFxQA40_3_F',
 'elavQFxattp2_1_M',
 'SwedArc>alrmF',
 'SwedArc>alrmM',
 'Londonxalrm_2_M',
 'attp2>nsybG4vF',
 'attp2xQA42_3_M',
 'attp40xQA42_3_M',
 'SwedArc>alrmF',
 'elavQFxattp40_3_M',
 'attp40xQAb40_F',
 'Londonxalrm_1_M',
 'attp2xQA40_3_M',
 'Swed>alrmF',
 'London>nsybG4vF',
 'SwedArc>alrmM',
 'Swed>nsybG4vF',
 nan,
 'attp2xrepo_2_M',
 'alrm>attp2M',
 'Londonxrepo_1_F',
 'London>alrmF',
 'Swedishxrepo_1_M',
 'elavQFxQAb40_F',
 'attp2xQA42_1_F',
 'London>alrmF',
 'attp40xQAb42_M',
 'elavQFxattp2_1_F',
 'Londonxattp40_2_F',
 'elavQFxattp40_3_F',
 'Swed>nsybG4vF',
 'Swed>attp2M',
 'Londonxrepo_3_M',
 'Londonxattp2_3_F',
 'Swedishxrepo_2_M',
 'Londonxalrm_3_F',
 'attp40xQAb40_M',
 'SwedArc>nsybG4m',
 'elav>attp2M',
 'SwedArc>attp2vF',
 'SwedArc>attp2M',
 'attp2xQA42_3_M',
 'SwedArc>attp2M')

In [21]:
data_test, fly_id_test, genotype_test = next(iter(test_loader))
print(data_test.shape)
print(len(fly_id_test))
print(len(genotype_test))

torch.Size([1363, 5017])
1363
1363