In [148]:
from vae import*
from utils import*
import pandas as pd
#from data_builder_no_labels import DataBuilder
from torch.utils.data import DataLoader
import sys
import os 
from collections import Counter

In [149]:
from utils import*
from torch.utils.data import Dataset
import torch

class DataBuilder(Dataset):
    def __init__(self, data):
        self.features = data.iloc[:, 1:-1].values.astype('float32')
        self.mouse_ids = data['MouseID']

    def __getitem__(self, index):
        return self.features[index], self.mouse_ids[index]
    
    def __len__(self):
        return len(self.features)

In [150]:
ex = pd.read_csv('/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/nature_filtered_nonan_nocfc.csv')
#ex.iloc[:, 1:-1]
ex

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2_Wheel_AvgDistLFC,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet
0,DO-40-2126,26,1541,29.523513,31.341861,27.520384,161.603172,84.828525,53.462304,516.996301,...,-0.103605,0.140082,197.287795,171.740018,99.647222,0.051882,0.172374,0.166289,1,40
1,DO-40-2117,26,1533,25.635280,28.483440,28.120159,146.162810,68.658928,67.881061,449.140753,...,1.872995,0.931612,194.905295,154.168518,177.974722,0.189739,0.177600,0.248073,1,40
2,DO-40-2118,26,1477,36.058736,37.270076,29.312845,154.814065,102.302694,67.881061,506.097998,...,0.162894,0.241456,181.205295,169.655518,173.209722,0.075896,0.215548,0.286021,1,40
3,DO-40-2115,26,1465,26.111027,24.494062,20.748181,152.891564,82.116435,55.384805,478.315657,...,2.604665,3.152223,160.655795,138.979518,111.858222,0.250546,0.181486,0.232985,1,40
4,DO-40-2070,24,1540,19.467849,20.099654,20.155893,136.404410,84.241603,96.770388,524.934223,...,1.949493,2.261991,129.318957,137.733391,135.754764,0.114761,0.177377,0.263152,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,DO-AL-0009,22,349,21.131405,63.024938,67.590983,140.940870,255.344186,261.476515,491.072949,...,-6.656427,-2.736010,250.583787,66.013018,58.352082,0.301015,0.480959,0.555556,5,AL
429,DO-1D-3015,22,309,30.660285,63.024938,67.590983,152.928679,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,163.396287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D
430,DO-2D-4010,22,309,20.517814,63.024938,67.590983,144.277424,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,173.202287,66.013018,58.352082,0.301015,0.480959,0.555556,3,2D
431,DO-1D-3006,22,244,26.757601,63.024938,67.590983,112.556159,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,104.987287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D
432,DO-20-1031,22,206,36.962136,63.024938,67.590983,163.144240,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,226.484573,66.013018,58.352082,0.301015,0.480959,0.555556,2,20

In [151]:
trained_model_path = '/Users/racheliritani/Desktop/AD Project/mm-vae/results_DIET/CGMVAE_cfc_cond_5bins_5dim/saved_model_epoch5000.pth'
data_no_cfc_path = '/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/nature_filtered_nonan_nocfc.csv'
output_path = '/Users/racheliritani/Desktop/AD Project/mm-vae/cfc_pred/pseudo_labels_no_cfc.csv'
os.makedirs(output_path, exist_ok=True)
accelerator = True 

if accelerator:
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")
all_data = pd.read_csv(data_no_cfc_path)

test_set = DataBuilder(all_data)
test_loader = DataLoader(test_set, batch_size=1, shuffle=False)
model = torch.load(trained_model_path, map_location=device)
model.eval()

Using device: mps

CGMVAE(
  (label): Embedding(5, 1)
  (fc1): Linear(in_features=37, out_features=16, bias=True)
  (bn1): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc21): Linear(in_features=16, out_features=25, bias=True)
  (fc22): Linear(in_features=16, out_features=25, bias=True)
  (fc3): Linear(in_features=6, out_features=16, bias=True)
  (bn3): BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc4): Linear(in_features=16, out_features=36, bias=True)
)

In [152]:
gmm_centers = pd.read_csv('/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/results_DIET/5_gmm_center_5dims.csv')
gmm_centers = gmm_centers.iloc[:, 1:]
gmm_centers

     center1    center2    center3    center4    center5
0 -20.172264 -11.293541  -7.190775  -3.983031   9.463689
1 -22.702984 -20.301035 -12.269944  -6.019031   6.202443
2 -11.748712  -8.682820  -0.457847   7.194811  16.704256
3 -12.459927  -6.230437  -2.124611   6.765072  18.014086
4   2.927976   5.914355  10.095953  21.043993  33.145348

In [154]:
labels_to_centers = np.array([0, 3, 2, 4, 1])

In [155]:
pseudo_labels = []
for batch_idx, (data, mouse_ids) in enumerate(test_loader):
    data = data.to(device)
    print(f'batch (sample) {batch_idx}: ')
    print(mouse_ids)
    #if batch_idx == 20:
    distance_to_centers = []
    for i in range(5):
        #print(f'label {i}')
        center_mapping = np.where(labels_to_centers == i)
        #print(f'associated_gmm_center_idx:{center_mapping[0][0]}')
        gmm_center = gmm_centers.iloc[:, center_mapping[0][0]]
        gmm_center_torch = torch.tensor(gmm_center.values, dtype=torch.float32)
        gmm_center_torch = gmm_center_torch.to(device)
        labels = torch.full((data.shape[0],), i, dtype=torch.int64)
        labels = labels.to(device)
        mu, logvar = model.encode(data, labels)
        # print(mu)
        #print('mu:')
        #print(mu[:, i])
        #print('center:')
        #print(gmm_center_torch)
        label_center = gmm_center_torch
        point_center = mu[:, i, :]
        diff = label_center-point_center
        squared_sum = torch.sum(diff.pow(2))
        label_dist = torch.sqrt(squared_sum)
        distance_to_centers.append(label_dist.item())
        #print('distance: ')
        #print(label_dist)
    #print(distance_to_centers)
    pseudo_label = np.argmin(np.array(distance_to_centers))
    pseudo_labels.append(pseudo_label)
    print(distance_to_centers)
    print(min(distance_to_centers))
    print(pseudo_label)

batch (sample) 0:
('DO-40-2126',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 1:
('DO-40-2117',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 2:
('DO-40-2118',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 3:
('DO-40-2115',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 4:
('DO-40-2070',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 5:
('DO-AL-0118',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 6:
('DO-40-2116',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 7:
('DO-20-1127',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 8:
('DO-20-1123',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 9:
('DO-40-2081',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 10:
('DO-20-1124',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 11:
('DO-2D-4113',)
[59.438045501708984, 13.919069290161133, 17.920955657958984, 46.97420120239258, 52.55961608886719]
13.919069290161133
1
batch (sample) 12:
('DO-40-2125',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 13:
('DO-20-1122',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 14:
('DO-20-1069',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 15:
('DO-2D-4122',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 16:
('DO-20-1066',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 17:
('DO-40-2124',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 18:
('DO-2D-4114',)
[54.70686340332031, 20.690229415893555, 11.774311065673828, 42.384864807128906, 46.63386535644531]
11.774311065673828
2
batch (sample) 19:
('DO-AL-0125',)
[54.70686340332031, 20.690229415893555, 11.774311065673828, 42.384864807128906, 46.63386535644531]
11.774311065673828
2
batch (sample) 20:
('DO-40-2123',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 21:
('DO-40-2073',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 22:
('DO-AL-0128',)
[54.70686340332031, 20.690229415893555, 11.774311065673828, 42.384864807128906, 46.63386535644531]
11.774311065673828
2
batch (sample) 23:
('DO-1D-3114',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 24:
('DO-40-2028',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 25:
('DO-AL-0117',)
[44.94900894165039, 34.92319869995117, 6.095197677612305, 33.572940826416016, 35.47263717651367]
6.095197677612305
2
batch (sample) 26:
('DO-40-2077',)
[44.94900894165039, 34.92319869995117, 6.095197677612305, 33.572940826416016, 35.47263717651367]
6.095197677612305
2
batch (sample) 27:
('DO-20-1074',)
[44.94900894165039, 34.92319869995117, 6.095197677612305, 33.572940826416016, 35.47263717651367]
6.095197677612305
2
batch (sample) 28:
('DO-1D-3123',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 29:
('DO-AL-0119',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 30:
('DO-2D-4128',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 31:
('DO-1D-3116',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 32:
('DO-40-2114',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 33:
('DO-20-1071',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 34:
('DO-40-2113',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 35:
('DO-1D-3124',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 36:
('DO-1D-3072',)
[54.70686340332031, 20.690229415893555, 11.774311065673828, 42.384864807128906, 46.63386535644531]
11.774311065673828
2
batch (sample) 37:
('DO-20-1128',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 38:
('DO-2D-4119',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 39:
('DO-20-1116',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 40:
('DO-20-1126',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 41:
('DO-20-1065',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 42:
('DO-2D-4124',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 43:
('DO-AL-0115',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 44:
('DO-1D-3074',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 45:
('DO-2D-4079',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 46:
('DO-1D-3118',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 47:
('DO-2D-4123',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 48:
('DO-20-1067',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 49:
('DO-20-1119',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 50:
('DO-40-2066',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 51:
('DO-40-2078',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 52:
('DO-40-2065',)
[44.94900894165039, 34.92319869995117, 6.095197677612305, 33.572940826416016, 35.47263717651367]
6.095197677612305
2
batch (sample) 53:
('DO-40-2067',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 54:
('DO-2D-4072',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 55:
('DO-1D-3117',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 56:
('DO-20-1115',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 57:
('DO-1D-3119',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 58:
('DO-1D-3120',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 59:
('DO-2D-4188',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 60:
('DO-2D-4189',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 61:
('DO-40-2180',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 62:
('DO-1D-3075',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 63:
('DO-20-1117',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 64:
('DO-1D-3184',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 65:
('DO-40-2185',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 66:
('DO-AL-0177',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 67:
('DO-40-2188',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 68:
('DO-2D-4117',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 69:
('DO-AL-0066',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 70:
('DO-2D-4176',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 71:
('DO-AL-0167',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 72:
('DO-20-1120',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 73:
('DO-20-1022',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 74:
('DO-40-2069',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 75:
('DO-AL-0122',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 76:
('DO-AL-0189',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 77:
('DO-40-2068',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 78:
('DO-20-1166',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 79:
('DO-AL-0164',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 80:
('DO-20-1192',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 81:
('DO-AL-0182',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 82:
('DO-2D-4127',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 83:
('DO-20-1078',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 84:
('DO-AL-0174',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 85:
('DO-2D-4116',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 86:
('DO-2D-4154',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 87:
('DO-2D-4181',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 88:
('DO-2D-4187',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 89:
('DO-AL-0068',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 90:
('DO-AL-0165',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 91:
('DO-AL-0071',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 92:
('DO-1D-3121',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 93:
('DO-AL-0123',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 94:
('DO-20-1133',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 95:
('DO-2D-4121',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 96:
('DO-1D-3066',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 97:
('DO-20-1079',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 98:
('DO-40-2075',)
[54.70686340332031, 20.690229415893555, 11.774311065673828, 42.384864807128906, 46.63386535644531]
11.774311065673828
2
batch (sample) 99:
('DO-40-2131',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 100:
('DO-40-2072',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 101:
('DO-2D-4179',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 102:
('DO-2D-4071',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 103:
('DO-AL-0138',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 104:
('DO-AL-0030',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 105:
('DO-AL-0170',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 106:
('DO-20-1141',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 107:
('DO-AL-0134',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 108:
('DO-1D-3132',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 109:
('DO-AL-0127',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 110:
('DO-40-2139',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 111:
('DO-20-1184',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 112:
('DO-1D-3076',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 113:
('DO-1D-3186',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 114:
('DO-2D-4156',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 115:
('DO-AL-0159',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 116:
('DO-AL-0169',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 117:
('DO-AL-0114',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 118:
('DO-1D-3133',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 119:
('DO-20-1075',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 120:
('DO-1D-3158',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 121:
('DO-1D-3167',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 122:
('DO-40-2173',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 123:
('DO-1D-3172',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 124:
('DO-2D-4125',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 125:
('DO-1D-3176',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 126:
('DO-40-2023',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 127:
('DO-1D-3071',)
[65.16738891601562, 7.251326560974121, 24.56241798400879, 51.706199645996094, 58.49348831176758]
7.251326560974121
1
batch (sample) 128:
('DO-2D-4134',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 129:
('DO-1D-3024',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 130:
('DO-2D-4115',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 131:
('DO-2D-4170',)
[69.96627807617188, 3.654996871948242, 26.13920021057129, 48.7436637878418, 54.38074493408203]
3.654996871948242
1
batch (sample) 132:
('DO-40-2142',)

In [156]:
for batch_idx, (data, mouse_ids) in enumerate(test_loader):
    print('batch_idx: ' + str(batch_idx))
    print('data: ' + str(data))
    print('mouse_id: ' + str(mouse_ids))

batch_idx: 0
data: tensor([[ 2.6000e+01,  1.5410e+03,  2.9524e+01,  3.1342e+01,  2.7520e+01,
          1.6160e+02,  8.4829e+01,  5.3462e+01,  5.1700e+02,  4.3636e+02,
          5.1253e+02,  1.5957e+04,  1.5244e+04,  1.8299e+04,  1.8508e+01,
          1.8025e+01,  1.2654e+01,  1.3187e+02,  2.0043e+02,  2.2545e+02,
          1.6444e+00,  1.4039e+00,  1.0852e+00, -1.7420e-01, -6.6592e-02,
         -1.1120e-01,  2.0675e-01, -1.0361e-01,  1.4008e-01,  1.9729e+02,
          1.7174e+02,  9.9647e+01,  5.1882e-02,  1.7237e-01,  1.6629e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2126',)
batch_idx: 1
data: tensor([[2.6000e+01, 1.5330e+03, 2.5635e+01, 2.8483e+01, 2.8120e+01, 1.4616e+02,
         6.8659e+01, 6.7881e+01, 4.4914e+02, 4.8485e+02, 4.2804e+02, 2.0088e+04,
         1.5067e+04, 1.7329e+04, 1.6249e+01, 1.6511e+01, 1.5013e+01, 2.6720e+02,
         2.4364e+02, 1.6003e+02, 1.7530e+00, 1.7631e+00, 1.5935e+00, 3.4138e-02,
         3.9506e-01, 3.4892e-01, 1.1956e+00, 1.8730e+00, 9.3161e-01, 1.9491e+02,
         1.5417e+02, 1.7797e+02, 1.8974e-01, 1.7760e-01, 2.4807e-01, 1.0000e+00]])
mouse_id: ('DO-40-2117',)
batch_idx: 2
data: tensor([[ 2.6000e+01,  1.4770e+03,  3.6059e+01,  3.7270e+01,  2.9313e+01,
          1.5481e+02,  1.0230e+02,  6.7881e+01,  5.0610e+02,  5.7664e+02,
          5.0733e+02,  1.6712e+04,  2.6172e+04,  2.1143e+04,  1.5974e+01,
          1.5704e+01,  1.4559e+01,  5.0384e+01,  8.7377e+01,  1.8488e+02,
          1.3057e+00,  1.3789e+00,  1.2426e+00, -2.4823e-01,  3.2886e-02,
         -9.3262e-02,  7.4869e-01,  1.6289e-01,  2.4146e-01,  1.8121e+02,
          1.6966e+02,  1.7321e+02,  7.5896e-02,  2.1555e-01,  2.8602e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2118',)
batch_idx: 3
data: tensor([[2.6000e+01, 1.4650e+03, 2.6111e+01, 2.4494e+01, 2.0748e+01, 1.5289e+02,
         8.2116e+01, 5.5385e+01, 4.7832e+02, 4.9340e+02, 4.5512e+02, 1.6386e+04,
         2.0767e+04, 1.6304e+04, 1.7713e+01, 1.7521e+01, 1.6558e+01, 1.1494e+02,
         1.7908e+02, 2.4944e+02, 1.3791e+00, 1.4955e+00, 1.0018e+00, 7.6746e-01,
         2.4954e-01, 9.4485e-01, 1.8080e+00, 2.6047e+00, 3.1522e+00, 1.6066e+02,
         1.3898e+02, 1.1186e+02, 2.5055e-01, 1.8149e-01, 2.3299e-01, 1.0000e+00]])
mouse_id: ('DO-40-2115',)
batch_idx: 4
data: tensor([[ 2.4000e+01,  1.5400e+03,  1.9468e+01,  2.0100e+01,  2.0156e+01,
          1.3640e+02,  8.4242e+01,  9.6770e+01,  5.2493e+02,  5.2069e+02,
          4.8489e+02,  1.8664e+04,  1.2735e+04,  2.0589e+04,  1.7051e+01,
          1.6315e+01,  1.5905e+01,  2.1666e+02,  2.4546e+02,  2.1479e+02,
          1.3692e+00,  1.4892e+00,  1.2382e+00, -4.9027e+00,  2.2225e-01,
          2.1803e-01, -4.2997e+00,  1.9495e+00,  2.2620e+00,  1.2932e+02,
          1.3773e+02,  1.3575e+02,  1.1476e-01,  1.7738e-01,  2.6315e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2070',)
batch_idx: 5
data: tensor([[ 2.6000e+01,  1.2930e+03,  2.1623e+01,  3.8876e+01,  3.9015e+01,
          1.9615e+02,  1.8882e+02,  1.8900e+02,  4.5250e+02,  4.7238e+02,
          4.7978e+02,  1.9012e+04,  2.6326e+04,  3.0014e+04,  1.6340e+01,
          1.4594e+01,  1.4196e+01,  1.4208e+02,  1.5279e+02,  4.4048e+01,
          1.6798e+00,  1.6942e+00,  1.4610e+00,  2.2369e-02,  8.2938e-01,
         -6.0172e-03,  6.7322e-01,  6.4638e-01,  4.2709e-01,  2.1129e+02,
          1.2826e+02,  1.1335e+02,  7.5896e-02,  2.5350e-01,  2.6705e-01,
          5.0000e+00]])
mouse_id: ('DO-AL-0118',)
batch_idx: 6
data: tensor([[2.6000e+01, 1.2620e+03, 2.3636e+01, 2.9207e+01, 2.8107e+01, 1.7308e+02,
         7.2504e+01, 7.1726e+01, 5.5311e+02, 4.8654e+02, 5.3258e+02, 1.4484e+04,
         8.3145e+03, 1.6364e+04, 1.7072e+01, 1.7319e+01, 1.6194e+01, 1.1152e+02,
         1.7079e+02, 1.1461e+02, 1.6142e+00, 1.4839e+00, 1.4004e+00, 6.0481e-02,
         1.6137e-02, 3.6143e-02, 7.9810e-01, 5.3155e-01, 3.5444e-01, 1.3713e+02,
         1.2707e+02, 1.3628e+02, 1.5179e-01, 1.7760e-01, 2.6705e-01, 1.0000e+00]])
mouse_id: ('DO-40-2116',)
batch_idx: 7
data: tensor([[2.6000e+01, 1.2590e+03, 2.3556e+01, 3.1554e+01, 2.9542e+01, 1.5481e+02,
         1.2153e+02, 8.8067e+01, 5.2320e+02, 5.3966e+02, 4.8286e+02, 1.8969e+04,
         1.5743e+04, 1.9181e+04, 1.7530e+01, 1.7420e+01, 1.6467e+01, 1.5922e+02,
         1.3080e+02, 1.0090e+02, 1.5375e+00, 1.4988e+00, 1.0491e+00, 2.9018e-01,
         1.4660e-01, 1.1832e-02, 1.8678e+00, 2.0607e+00, 1.1675e+00, 1.6483e+02,
         1.7353e+02, 1.5743e+02, 1.3282e-01, 1.7760e-01, 1.9115e-01, 2.0000e+00]])
mouse_id: ('DO-20-1127',)
batch_idx: 8
data: tensor([[2.6000e+01, 1.2490e+03, 3.3831e+01, 3.9994e+01, 3.9288e+01, 2.2499e+02,
         1.1672e+02, 9.6719e+01, 5.7951e+02, 5.3282e+02, 5.3833e+02, 2.6395e+04,
         2.6250e+04, 2.2108e+04, 1.8079e+01, 1.7117e+01, 9.5726e+00, 2.3007e+02,
         2.1907e+02, 1.5432e+02, 1.8419e+00, 1.6455e+00, 1.5756e+00, 3.9080e-01,
         8.0582e-02, 2.5898e-01, 1.5351e+00, 6.5053e-01, 1.0355e+00, 2.1009e+02,
         1.9795e+02, 1.9793e+02, 7.5896e-02, 2.1555e-01, 2.6705e-01, 2.0000e+00]])
mouse_id: ('DO-20-1123',)
batch_idx: 9
data: tensor([[ 2.4000e+01,  1.4290e+03,  3.2474e+01,  3.6723e+01,  3.2788e+01,
          1.8105e+02,  8.7553e+01,  7.8944e+01,  5.3414e+02,  5.4644e+02,
          4.9694e+02,  2.7139e+04,  2.8131e+04,  2.3291e+04,  1.5511e+01,
          1.2759e+01,  1.5190e+01,  1.8560e+02,  1.1848e+02,  7.4691e+01,
          1.5753e+00,  1.5650e+00,  1.4174e+00,  9.8194e-02, -2.6611e-01,
          5.6673e-02,  1.1250e+00, -7.2191e-01,  3.7702e-01,  2.3343e+02,
          1.9515e+02,  1.7634e+02,  1.3582e-01,  1.7599e-01,  2.0322e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2081',)
batch_idx: 10
data: tensor([[ 2.6000e+01,  1.2160e+03,  2.0186e+01,  3.3331e+01,  3.1265e+01,
          1.1829e+02,  8.5961e+01,  8.3261e+01,  5.2192e+02,  5.8382e+02,
          5.1606e+02,  1.6281e+04,  1.6663e+04,  1.9744e+04,  1.8354e+01,
          1.8431e+01,  1.8287e+01,  1.3780e+02,  8.3663e+01,  1.0061e+02,
          1.5754e+00,  1.4469e+00,  1.2946e+00,  1.5914e-01, -2.2413e-02,
          1.6687e-02,  1.7082e+00,  8.2378e-01,  7.6357e-01,  1.4606e+02,
          1.3779e+02,  1.8244e+02,  9.4869e-02,  1.7760e-01,  2.2910e-01,
          2.0000e+00]])
mouse_id: ('DO-20-1124',)
batch_idx: 11
data: tensor([[2.6000e+01, 1.2060e+03, 3.5917e+01, 4.6586e+01, 4.4146e+01, 1.5007e+02,
         1.3289e+02, 1.1210e+02, 5.4227e+02, 5.3486e+02, 5.1079e+02, 3.3821e+04,
         2.4472e+04, 2.6305e+04, 1.6295e+01, 1.4969e+01, 1.4196e+01, 2.2786e+02,
         2.3500e+02, 1.3518e+02, 1.1455e+00, 1.2829e+00, 1.3638e+00, 8.7189e-01,
         1.2432e+00, 3.3716e-01, 2.0451e+00, 1.4284e+00, 1.1380e+00, 2.3630e+02,
         2.6138e+02, 1.0858e+02, 1.6961e-01, 1.9523e-01, 2.4607e-01, 3.0000e+00]])
mouse_id: ('DO-2D-4113',)
batch_idx: 12
data: tensor([[ 2.6000e+01,  1.1890e+03,  2.5505e+01,  2.4154e+01,  2.4720e+01,
          1.4334e+02,  7.4255e+01,  9.6719e+01,  5.1246e+02,  5.0589e+02,
          5.6908e+02,  1.9598e+04,  2.2246e+04,  2.6961e+04,  1.6479e+01,
          1.7005e+01,  1.6740e+01,  1.6158e+02,  2.2728e+02,  2.4659e+02,
          1.1569e+00,  1.3500e+00,  1.2156e+00,  4.7109e-01,  4.2821e-01,
         -1.4239e-01,  2.0172e+00,  2.0181e+00, -4.9002e-01,  1.4904e+02,
          1.5804e+02,  1.1394e+02,  1.2778e-01,  1.9135e-01,  2.6116e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2125',)
batch_idx: 13
data: tensor([[ 2.6000e+01,  1.1680e+03,  2.7913e+01,  3.6549e+01,  3.2772e+01,
          1.6539e+02,  1.0903e+02,  1.0152e+02,  5.0405e+02,  5.1710e+02,
          5.0223e+02,  1.8549e+04,  2.2030e+04,  1.8866e+04,  1.7804e+01,
          1.6915e+01,  1.0750e+01,  1.1866e+02,  1.1566e+02,  1.1432e+02,
          1.4460e+00,  1.3466e+00,  1.4046e+00,  9.1726e-02, -1.6000e-01,
         -1.3698e-02,  1.3978e+00,  1.6365e-01,  6.0600e-01,  1.9401e+02,
          1.5685e+02,  1.2020e+02,  1.3282e-01,  1.9657e-01,  2.1013e-01,
          2.0000e+00]])
mouse_id: ('DO-20-1122',)
batch_idx: 14
data: tensor([[ 2.4000e+01,  1.3740e+03,  2.6450e+01,  3.2471e+01,  3.0136e+01,
          1.0084e+02,  1.5537e+02,  1.1792e+02,  6.0389e+02,  5.0354e+02,
          5.2054e+02,  2.5015e+04,  1.6583e+04,  2.5445e+04,  1.6373e+01,
          1.5642e+01,  1.4406e+01,  2.4151e+02,  1.6061e+02,  2.4279e+02,
          1.8869e+00,  1.5757e+00,  1.3187e+00,  9.2862e-02, -4.2357e-03,
          1.8037e-01,  1.7051e+00,  1.3006e+00,  1.2246e+00,  1.9544e+02,
          2.4528e+02,  1.4856e+02,  1.3373e-01,  1.7738e-01,  2.0623e-01,
          2.0000e+00]])
mouse_id: ('DO-20-1069',)
batch_idx: 15
data: tensor([[ 2.6000e+01,  1.1600e+03,  3.0577e+01,  4.2250e+01,  4.3285e+01,
          1.5680e+02,  1.5692e+02,  1.6593e+02,  4.9288e+02,  5.0772e+02,
          5.4420e+02,  1.6453e+04,  2.4202e+04,  2.8123e+04,  1.6295e+01,
          1.5986e+01,  1.4105e+01,  9.9021e+01,  1.3958e+02,  5.7474e+01,
          1.5741e+00,  1.6456e+00,  1.4252e+00,  7.9085e-02, -7.3495e-02,
          5.8874e-01,  8.8265e-02,  3.6449e-01,  6.1764e-01,  2.0980e+02,
          2.0003e+02,  2.1878e+02,  7.0856e-02,  2.2930e-01,  2.0424e-01,
          3.0000e+00]])
mouse_id: ('DO-2D-4122',)
batch_idx: 16
data: tensor([[2.4000e+01, 1.3620e+03, 2.0662e+01, 2.3905e+01, 2.2268e+01, 1.6332e+02,
         1.6499e+02, 7.5623e+01, 5.7662e+02, 5.4413e+02, 4.8221e+02, 1.2505e+04,
         1.6174e+04, 1.7159e+04, 1.7244e+01, 1.6218e+01, 1.5717e+01, 2.1923e+02,
         2.7317e+02, 2.1594e+02, 1.3696e+00, 1.1782e+00, 1.2179e+00, 7.5694e-01,
         6.1537e-01, 3.7913e-01, 1.6901e+00, 1.6185e+00, 1.4697e+00, 2.0794e+02,
         1.8658e+02, 9.9122e+01, 1.3373e-01, 1.7738e-01, 2.6315e-01, 2.0000e+00]])
mouse_id: ('DO-20-1066',)
batch_idx: 17
data: tensor([[ 2.6000e+01,  1.1550e+03,  2.5556e+01,  2.0765e+01,  2.0748e+01,
          1.2219e+02,  5.5030e+01,  7.2687e+01,  4.4748e+02,  4.4614e+02,
          4.7825e+02,  1.5660e+04,  2.1380e+04,  1.9548e+04,  1.7032e+01,
          1.6449e+01,  1.3924e+01,  2.2386e+02,  1.0845e+02,  1.6803e+02,
          1.2387e+00,  1.2253e+00,  1.1911e+00, -1.7838e-02,  1.5245e-01,
         -1.4062e-01,  9.2557e-01,  8.5711e-01, -1.3349e+00,  1.6836e+02,
          1.5893e+02,  1.4373e+02,  7.0856e-02,  1.9135e-01,  3.7500e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2124',)
batch_idx: 18
data: tensor([[2.6000e+01, 1.1460e+03, 2.0533e+01, 2.7252e+01, 2.7544e+01, 1.7122e+02,
         1.4443e+02, 1.1114e+02, 5.2815e+02, 4.8654e+02, 5.3448e+02, 2.5271e+04,
         1.5559e+04, 2.2702e+04, 1.6479e+01, 1.5616e+01, 1.3289e+01, 1.8158e+02,
         2.2585e+02, 2.0831e+02, 1.4861e+00, 1.5496e+00, 1.4827e+00, 3.4359e-01,
         3.0053e-01, 2.6152e-02, 7.8194e-01, 6.4118e-01, 2.4435e-01, 1.9133e+02,
         1.4643e+02, 1.4909e+02, 8.9830e-02, 1.5340e-01, 1.6629e-01, 3.0000e+00]])
mouse_id: ('DO-2D-4114',)
batch_idx: 19
data: tensor([[2.6000e+01, 1.1380e+03, 3.0387e+01, 4.2222e+01, 3.7672e+01, 1.5962e+02,
         1.5902e+02, 1.6881e+02, 4.9404e+02, 5.1558e+02, 5.1606e+02, 2.9487e+04,
         1.7061e+04, 2.3559e+04, 1.2961e+01, 1.4796e+01, 1.4196e+01, 1.4951e+02,
         1.6708e+02, 2.0116e+02, 1.4490e+00, 1.3630e+00, 1.0923e+00, 2.3338e-01,
         1.3272e-01, 3.8040e-01, 4.8160e-01, 9.5446e-01, 2.0996e+00, 2.0950e+02,
         1.7025e+02, 1.2466e+02, 1.5179e-01, 1.9657e-01, 3.2397e-01, 5.0000e+00]])
mouse_id: ('DO-AL-0125',)
batch_idx: 20
data: tensor([[2.6000e+01, 1.1320e+03, 2.6259e+01, 2.3458e+01, 2.4026e+01, 1.5391e+02,
         9.3480e+01, 8.1339e+01, 4.4240e+02, 4.4190e+02, 3.8757e+02, 1.7378e+04,
         1.8071e+04, 1.5756e+04, 1.6940e+01, 1.7190e+01, 1.5286e+01, 2.4871e+02,
         2.6299e+02, 2.3345e+02, 1.4463e+00, 1.2056e+00, 1.0465e+00, 2.7487e-02,
         4.0583e-02, 2.7065e-01, 5.1373e-01, 5.2805e-01, 7.1890e-01, 1.7674e+02,
         1.4196e+02, 8.8032e+01, 7.0856e-02, 1.3443e-01, 2.6116e-01, 1.0000e+00]])
mouse_id: ('DO-40-2123',)
batch_idx: 21
data: tensor([[ 2.4000e+01,  1.3280e+03,  2.7504e+01,  2.1992e+01,  2.2471e+01,
          1.0925e+02,  4.6753e+01,  6.1204e+01,  4.1506e+02,  3.6896e+02,
          4.1618e+02,  1.6129e+04,  1.0908e+04,  1.4050e+04,  1.7168e+01,
          1.6061e+01,  1.5061e+01,  2.0755e+02,  2.8688e+02,  2.1422e+02,
          1.4111e+00,  1.2281e+00,  1.1460e+00, -4.9027e+00,  1.8927e-01,
          1.3051e-01, -4.2997e+00,  1.3264e+00,  5.3313e-01,  1.5612e+02,
          1.3773e+02,  1.1580e+02,  1.1129e-01,  2.2242e-01,  2.2909e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2073',)
batch_idx: 22
data: tensor([[2.6000e+01, 1.1170e+03, 2.3497e+01, 3.5385e+01, 3.1831e+01, 1.9038e+02,
         1.8113e+02, 1.9765e+02, 5.2868e+02, 5.2294e+02, 4.4970e+02, 2.5410e+04,
         1.9450e+04, 1.4776e+04, 1.4878e+01, 1.3587e+01, 1.4196e+01, 2.7206e+02,
         2.4421e+02, 1.7774e+02, 1.5131e+00, 1.5123e+00, 1.0218e+00, 6.9949e-02,
         2.5647e-01, 3.2031e-01, 9.5126e-01, 9.2638e-01, 1.1083e+00, 2.0741e+02,
         1.5000e+02, 9.6967e+01, 9.4869e-02, 1.5863e-01, 2.2910e-01, 5.0000e+00]])
mouse_id: ('DO-AL-0128',)
batch_idx: 23
data: tensor([[2.6000e+01, 1.1160e+03, 2.3339e+01, 3.6283e+01, 3.4089e+01, 1.9525e+02,
         1.4923e+02, 1.2363e+02, 4.4377e+02, 4.4652e+02, 4.3294e+02, 1.5654e+04,
         1.2552e+04, 1.1991e+04, 1.6295e+01, 1.3120e+01, 1.4922e+01, 1.6130e+02,
         1.1759e+02, 1.0661e+02, 1.7048e+00, 1.9133e+00, 1.3801e+00, 3.7957e-01,
         3.9475e-01, 2.9902e-01, 1.7233e+00, 8.1346e-01, 7.7625e-01, 1.6036e+02,
         1.2171e+02, 1.7053e+02, 1.3166e-01, 1.7626e-01, 2.4607e-01, 4.0000e+00]])
mouse_id: ('DO-1D-3114',)
batch_idx: 24
data: tensor([[ 2.2000e+01,  1.5210e+03,  1.8181e+01,  1.9043e+01,  1.9427e+01,
          1.3740e+02,  7.3958e+01,  1.2247e+02,  4.4170e+02,  4.2722e+02,
          4.9327e+02,  1.5933e+04,  1.1913e+04,  1.2924e+04,  1.8011e+01,
          1.7334e+01,  1.7262e+01,  1.7437e+02,  2.5086e+02,  4.2900e+01,
          1.6937e+00,  1.7312e+00,  1.4484e+00,  8.2789e-01,  1.9644e-01,
         -8.8509e-02,  2.4424e+00,  4.9228e-01,  3.3483e-01,  1.9025e+02,
          1.6605e+02,  1.3868e+02,  3.0101e-01,  2.2619e-01,  3.0271e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2028',)
batch_idx: 25
data: tensor([[ 2.6000e+01,  1.1110e+03,  2.3026e+01,  3.5146e+01,  3.3075e+01,
          1.7116e+02,  1.7151e+02,  1.5247e+02,  5.7556e+02,  4.7698e+02,
          4.8286e+02,  2.2066e+04,  6.9713e+03,  1.7846e+04,  1.5335e+01,
          1.4090e+01,  1.2563e+01,  1.4922e+02,  1.1080e+02,  1.5374e+02,
          1.5041e+00,  1.6651e+00,  1.1993e+00,  5.1276e-02, -1.0295e-01,
          9.3580e-02,  2.4327e-01,  7.1081e-01,  6.3628e-01,  1.7108e+02,
          1.8753e+02,  9.3095e+01,  1.1384e-01,  2.1555e-01,  3.4294e-01,
          5.0000e+00]])
mouse_id: ('DO-AL-0117',)
batch_idx: 26
data: tensor([[ 2.4000e+01,  1.3100e+03,  2.7068e+01,  2.2012e+01,  2.0442e+01,
          1.4097e+02,  5.8288e+01,  5.4475e+01,  6.8182e+02,  4.8269e+02,
          5.1696e+02,  3.9517e+04,  1.3326e+04,  2.4097e+04,  1.6783e+01,
          1.7053e+01,  1.6936e+01,  2.0012e+02,  1.6233e+02,  1.9937e+02,
          1.5377e+00,  1.4171e+00,  1.3664e+00, -4.9027e+00,  5.1225e-01,
          9.0414e-01, -4.2997e+00,  2.1375e+00,  2.0175e+00,  1.9156e+02,
          1.8663e+02,  1.1461e+02,  1.0740e-01,  1.8058e-01,  2.6315e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2077',)
batch_idx: 27
data: tensor([[ 2.4000e+01,  1.3150e+03,  2.8581e+01,  4.2200e+01,  3.9694e+01,
          1.4794e+02,  1.8710e+02,  1.1792e+02,  5.3065e+02,  5.0354e+02,
          5.3365e+02,  2.6473e+04,  1.6241e+04,  1.5457e+04,  1.6373e+01,
          1.7276e+01,  1.5530e+01,  7.5541e+01,  8.9769e+01,  8.8243e+01,
          1.5069e+00,  1.7419e+00,  1.4094e+00,  2.0384e-01, -1.0302e-01,
          8.3369e-02,  1.3414e+00,  3.4766e-01,  5.0202e-01,  2.0616e+02,
          1.9818e+02,  1.7120e+02,  1.7168e-01,  1.9635e-01,  3.7700e-01,
          2.0000e+00]])
mouse_id: ('DO-20-1074',)
batch_idx: 28
data: tensor([[2.6000e+01, 1.0920e+03, 2.4308e+01, 3.0243e+01, 4.2871e+01, 1.6737e+02,
         1.2328e+02, 9.7680e+01, 4.7952e+02, 5.1740e+02, 4.5104e+02, 2.0795e+04,
         1.7790e+04, 2.2371e+04, 1.3351e+01, 1.5431e+01, 1.5104e+01, 2.7699e+02,
         1.0245e+02, 1.5917e+02, 1.4481e+00, 1.6729e+00, 1.0793e+00, 6.9346e-01,
         3.4115e-01, 4.1016e-01, 2.2097e+00, 1.0293e+00, 1.2821e+00, 2.0563e+02,
         2.3190e+02, 1.2883e+02, 3.2908e-02, 2.1032e-01, 1.8526e-01, 4.0000e+00]])
mouse_id: ('DO-1D-3123',)
batch_idx: 29
data: tensor([[2.6000e+01, 1.0920e+03, 2.0861e+01, 3.4765e+01, 3.6000e+01, 1.4328e+02,
         1.9362e+02, 1.9188e+02, 4.6625e+02, 4.5908e+02, 5.3448e+02, 1.6138e+04,
         2.1027e+04, 2.2294e+04, 1.6797e+01, 1.5603e+01, 1.1838e+01, 3.9529e+01,
         6.1381e+01, 1.3346e+02, 1.4115e+00, 1.2948e+00, 1.1807e+00, 3.5548e-01,
         2.7318e-01, 2.4020e-02, 1.9829e+00, 1.2168e+00, 8.3091e-01, 1.5649e+02,
         1.8663e+02, 1.7202e+02, 7.5896e-02, 1.7760e-01, 2.8602e-01, 5.0000e+00]])
mouse_id: ('DO-AL-0119',)
batch_idx: 30
data: tensor([[2.6000e+01, 1.0820e+03, 2.4941e+01, 2.8716e+01, 2.6659e+01, 1.5391e+02,
         1.4346e+02, 1.2940e+02, 4.4517e+02, 5.6051e+02, 5.1606e+02, 1.6309e+04,
         1.9286e+04, 3.0043e+04, 1.6019e+01, 1.5524e+01, 1.4468e+01, 2.6042e+02,
         9.2449e+01, 1.2661e+02, 1.5660e+00, 1.3187e+00, 1.2064e+00, 1.9975e-01,
         1.3320e-01, 1.3260e-01, 3.0120e-01, 3.9741e-01, 5.6809e-01, 1.7197e+02,
         1.2200e+02, 1.3449e+02, 1.3587e-01, 1.9944e-01, 2.6925e-01, 3.0000e+00]])
mouse_id: ('DO-2D-4128',)
batch_idx: 31
data: tensor([[2.6000e+01, 1.0800e+03, 2.0443e+01, 2.5137e+01, 2.7016e+01, 1.9909e+02,
         1.9345e+02, 1.3325e+02, 4.6910e+02, 6.0058e+02, 5.3069e+02, 1.7688e+04,
         1.8493e+04, 2.1502e+04, 1.6479e+01, 1.6357e+01, 1.1928e+01, 2.7699e+02,
         2.6299e+02, 1.5289e+02, 1.6271e+00, 1.5294e+00, 1.3899e+00, 7.0296e-01,
         5.8382e-01, 2.5330e-01, 1.4428e+00, 9.2150e-01, 6.1777e-01, 1.6393e+02,
         1.2558e+02, 1.6249e+02, 8.9830e-02, 1.7237e-01, 1.8526e-01, 4.0000e+00]])
mouse_id: ('DO-1D-3116',)
batch_idx: 32
data: tensor([[2.6000e+01, 1.0780e+03, 2.5943e+01, 2.8629e+01, 2.6062e+01, 1.3367e+02,
         8.0194e+01, 7.0765e+01, 4.9831e+02, 5.1710e+02, 4.8756e+02, 1.5777e+04,
         2.5216e+04, 1.8512e+04, 1.6066e+01, 1.6107e+01, 1.4014e+01, 1.9265e+02,
         2.6478e+02, 2.5144e+02, 1.2785e+00, 1.2360e+00, 1.0327e+00, 3.9217e-01,
         8.5350e-01, 1.2134e-01, 7.4590e-01, 1.2180e+00, 7.9941e-01, 1.4457e+02,
         1.6638e+02, 1.0143e+02, 4.1834e-02, 1.8149e-01, 2.1401e-01, 1.0000e+00]])
mouse_id: ('DO-40-2114',)
batch_idx: 33
data: tensor([[ 2.4000e+01,  1.2830e+03,  2.7202e+01,  3.3439e+01,  3.0953e+01,
          1.7101e+02,  1.4480e+02,  1.2080e+02,  4.4722e+02,  4.9140e+02,
          4.4399e+02,  2.1909e+04,  2.4779e+04,  1.5997e+04,  1.7244e+01,
          1.6603e+01,  1.6748e+01,  1.5096e+02,  1.6147e+02,  2.0708e+02,
          1.8112e+00,  1.5248e+00,  1.3874e+00,  5.4413e-01,  9.5467e-02,
         -4.1793e-01,  2.3165e+00,  2.4047e+00, -8.5387e-01,  1.8263e+02,
          1.6838e+02,  1.8073e+02,  1.1476e-01,  1.9635e-01,  2.2520e-01,
          2.0000e+00]])
mouse_id: ('DO-20-1071',)
batch_idx: 34
data: tensor([[ 2.6000e+01,  1.0700e+03,  2.2428e+01,  2.5008e+01,  2.0697e+01,
          1.3559e+02,  8.3078e+01,  5.7307e+01,  3.9305e+02,  3.6435e+02,
          4.4180e+02,  1.4919e+04,  2.0235e+04,  1.3732e+04,  1.6797e+01,
          1.7117e+01,  2.2000e+00,  2.4978e+02,  2.1221e+02,  2.7544e+02,
          1.5792e+00,  1.4646e+00,  1.1001e+00,  6.9103e-01,  9.8540e-01,
         -6.2570e-02,  3.1068e+00,  3.3828e+00,  8.9354e-02,  2.1277e+02,
          1.9259e+02,  2.1222e+02,  1.9362e-01,  1.6251e-01,  1.9504e-01,
          1.0000e+00]])
mouse_id: ('DO-40-2113',)
batch_idx: 35
data: tensor([[ 2.6000e+01,  1.0520e+03,  2.6991e+01,  2.7402e+01,  2.6389e+01,
          1.6737e+02,  1.6750e+02,  1.6689e+02,  5.4740e+02,  5.6979e+02,
          4.9724e+02,  2.0796e+04,  2.9262e+04,  1.2262e+04,  1.5282e+01,
          1.3952e+01,  2.2000e+00,  8.6737e+01,  4.9313e+01,  1.8117e+02,

In [157]:
len(pseudo_labels)

433

In [158]:
counts = Counter(pseudo_labels)
print(counts)

Counter({1: 422, 2: 11})

In [122]:
all_data

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y2_Wheel_AvgDistLFC,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet
0,DO-40-2126,26,1541,29.523513,31.341861,27.520384,161.603172,84.828525,53.462304,516.996301,...,-0.103605,0.140082,197.287795,171.740018,99.647222,0.051882,0.172374,0.166289,1,40
1,DO-40-2117,26,1533,25.635280,28.483440,28.120159,146.162810,68.658928,67.881061,449.140753,...,1.872995,0.931612,194.905295,154.168518,177.974722,0.189739,0.177600,0.248073,1,40
2,DO-40-2118,26,1477,36.058736,37.270076,29.312845,154.814065,102.302694,67.881061,506.097998,...,0.162894,0.241456,181.205295,169.655518,173.209722,0.075896,0.215548,0.286021,1,40
3,DO-40-2115,26,1465,26.111027,24.494062,20.748181,152.891564,82.116435,55.384805,478.315657,...,2.604665,3.152223,160.655795,138.979518,111.858222,0.250546,0.181486,0.232985,1,40
4,DO-40-2070,24,1540,19.467849,20.099654,20.155893,136.404410,84.241603,96.770388,524.934223,...,1.949493,2.261991,129.318957,137.733391,135.754764,0.114761,0.177377,0.263152,1,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,DO-AL-0009,22,349,21.131405,63.024938,67.590983,140.940870,255.344186,261.476515,491.072949,...,-6.656427,-2.736010,250.583787,66.013018,58.352082,0.301015,0.480959,0.555556,5,AL
429,DO-1D-3015,22,309,30.660285,63.024938,67.590983,152.928679,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,163.396287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D
430,DO-2D-4010,22,309,20.517814,63.024938,67.590983,144.277424,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,173.202287,66.013018,58.352082,0.301015,0.480959,0.555556,3,2D
431,DO-1D-3006,22,244,26.757601,63.024938,67.590983,112.556159,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,104.987287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D
432,DO-20-1031,22,206,36.962136,63.024938,67.590983,163.144240,255.344186,261.476515,681.818182,...,-6.656427,-2.736010,226.484573,66.013018,58.352082,0.301015,0.480959,0.555556,2,20

In [124]:
all_data['pseudo_label'] = pseudo_labels
all_data

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y3_Wheel_AvgDistLFC,Y1A_Grip_All,Y2A_Grip_All,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet,pseudo_label
0,DO-40-2126,26,1541,29.523513,31.341861,27.520384,161.603172,84.828525,53.462304,516.996301,...,0.140082,197.287795,171.740018,99.647222,0.051882,0.172374,0.166289,1,40,0
1,DO-40-2117,26,1533,25.635280,28.483440,28.120159,146.162810,68.658928,67.881061,449.140753,...,0.931612,194.905295,154.168518,177.974722,0.189739,0.177600,0.248073,1,40,0
2,DO-40-2118,26,1477,36.058736,37.270076,29.312845,154.814065,102.302694,67.881061,506.097998,...,0.241456,181.205295,169.655518,173.209722,0.075896,0.215548,0.286021,1,40,0
3,DO-40-2115,26,1465,26.111027,24.494062,20.748181,152.891564,82.116435,55.384805,478.315657,...,3.152223,160.655795,138.979518,111.858222,0.250546,0.181486,0.232985,1,40,0
4,DO-40-2070,24,1540,19.467849,20.099654,20.155893,136.404410,84.241603,96.770388,524.934223,...,2.261991,129.318957,137.733391,135.754764,0.114761,0.177377,0.263152,1,40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,DO-AL-0009,22,349,21.131405,63.024938,67.590983,140.940870,255.344186,261.476515,491.072949,...,-2.736010,250.583787,66.013018,58.352082,0.301015,0.480959,0.555556,5,AL,2
429,DO-1D-3015,22,309,30.660285,63.024938,67.590983,152.928679,255.344186,261.476515,681.818182,...,-2.736010,163.396287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D,0
430,DO-2D-4010,22,309,20.517814,63.024938,67.590983,144.277424,255.344186,261.476515,681.818182,...,-2.736010,173.202287,66.013018,58.352082,0.301015,0.480959,0.555556,3,2D,3
431,DO-1D-3006,22,244,26.757601,63.024938,67.590983,112.556159,255.344186,261.476515,681.818182,...,-2.736010,104.987287,66.013018,58.352082,0.301015,0.480959,0.555556,4,1D,3
432,DO-20-1031,22,206,36.962136,63.024938,67.590983,163.144240,255.344186,261.476515,681.818182,...,-2.736010,226.484573,66.013018,58.352082,0.301015,0.480959,0.555556,2,20,0

In [159]:
# save csv with pseudo labels 
# all_data.to_csv('/Users/racheliritani/Desktop/AD Project/mm-vae/cfc_pred/data_no_cfc_pseudo_labels.csv', index=False)

In [160]:
pd.read_csv('/Users/racheliritani/Desktop/AD Project/VAE-work/c-gmvae/data_with_cfc_5bins.csv')

,MouseID,Generation,SurvDays,Y1A_BW_BW,Y2A_BW_BW,Y3A_BW_BW,Y1_Glu.F_Glucose,Y2_Glu.F_Glucose,Y3_Glu.F_Glucose,Y1_Echo_BPM,...,Y3A_Grip_All,Y1A_Frailty_FrailtyAdj,Y2A_Frailty_FrailtyAdj,Y3A_Frailty_FrailtyAdj,Diet_num,Diet_x,Diet_y,Mouse.ID,CFC.24mo.Average,cfc_bin
0,DO-40-2162,28,1611,24.787142,26.993230,23.645309,164.713839,134.572768,74.479328,499.174601,...,179.558615,0.032865,0.133616,0.159587,1,40,40,DO-40-2162,3.78,0
1,DO-40-2179,28,1557,30.432753,23.594599,23.529931,161.043852,71.901384,69.226421,495.841743,...,208.833723,0.183285,0.231782,0.235033,1,40,40,DO-40-2179,26.71,1
2,DO-40-2181,28,1533,20.747600,19.072890,20.528352,161.043852,93.048894,60.575167,520.949018,...,158.799723,0.069442,0.231782,0.197085,1,40,40,DO-40-2181,27.02,1
3,DO-40-2187,28,1520,25.977819,29.254446,30.242503,127.747193,85.358891,71.148922,466.210754,...,208.833223,0.106295,0.174654,0.216059,1,40,40,DO-40-2187,50.40,2
4,DO-40-2099,26,1638,24.242912,23.626717,22.912834,166.520150,72.692867,59.960123,464.789558,...,153.357082,0.110173,0.155822,0.285573,1,40,40,DO-40-2099,34.18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,DO-2D-4007,22,771,40.141463,46.980545,67.590983,112.556159,165.312618,261.476515,554.545551,...,58.352082,0.301015,0.209083,0.555556,3,2D,2D,DO-2D-4007,23.69,1
500,DO-1D-3030,22,748,24.315156,29.916707,67.590983,139.326564,136.439061,261.476515,544.317015,...,58.352082,0.301015,0.082493,0.555556,4,1D,1D,DO-1D-3030,29.78,1
501,DO-20-1021,22,738,30.809768,38.120260,67.590983,168.911742,152.502965,261.476515,542.558402,...,58.352082,0.301015,0.224366,0.555556,2,20,20,DO-20-1021,18.22,0
502,DO-AL-0002,22,755,30.261862,48.841393,67.590983,139.018370,125.113095,261.476515,477.144237,...,58.352082,0.301015,0.277963,0.555556,5,AL,AL,DO-AL-0002,57.42,2
503,DO-40-2006,22,750,22.588584,19.184004,67.590983,114.025857,60.709314,261.476515,472.837574,...,58.352082,0.301015,0.202068,0.555556,1,40,40,DO-40-2006,12.58,0